<a href="https://colab.research.google.com/github/chanakatb/pytorch_deep_learning/blob/main/Intro_To_Colab_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np

In [7]:
# !pip list

**LISTS**

In [14]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY**

In [18]:
np1 = np.random.rand(3,4)
np1


array([[0.08805052, 0.91724141, 0.32249837, 0.38419447],
       [0.77005187, 0.75897933, 0.52475677, 0.73301267],
       [0.2367085 , 0.31186173, 0.54856114, 0.73250874]])

In [19]:
np1.dtype

dtype('float64')

**TENSORS**

In [16]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7577, -0.2502,  0.3047,  1.9593],
        [-0.4629,  1.6065, -0.8094,  1.1585],
        [ 0.9713,  0.2725,  0.3932, -0.8754]])

In [20]:
tensor_2d.dtype

torch.float32

In [21]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
tensor_2d.dtype

torch.float32

In [22]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0881, 0.9172, 0.3225, 0.3842],
        [0.7701, 0.7590, 0.5248, 0.7330],
        [0.2367, 0.3119, 0.5486, 0.7325]], dtype=torch.float64)