<a href="https://colab.research.google.com/github/chanakatb/pytorch_deep_learning/blob/main/Intro_To_Colab_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Deep Learning with PyTorch 2**

In [106]:
import torch
import numpy as np

In [107]:
# !pip list

**LISTS**

In [108]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY**

In [109]:
np1 = np.random.rand(3,4)
np1


array([[0.99730078, 0.73179162, 0.3015152 , 0.88515402],
       [0.86046169, 0.31850044, 0.34969733, 0.17666187],
       [0.24772179, 0.08032976, 0.85009071, 0.17265435]])

In [110]:
np1.dtype

dtype('float64')

**TENSORS**

In [111]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.9679, -0.0186, -1.2768, -0.5260],
        [ 0.5066, -1.2101,  0.6807,  0.1685],
        [-0.3420,  1.3033,  1.8942,  2.3203]])

In [112]:
tensor_2d.dtype

torch.float32

In [113]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [114]:
tensor_2d.dtype

torch.float32

In [115]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9973, 0.7318, 0.3015, 0.8852],
        [0.8605, 0.3185, 0.3497, 0.1767],
        [0.2477, 0.0803, 0.8501, 0.1727]], dtype=torch.float64)

## **Deep Learning with PyTorch 3**

In [116]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
my_torch.dtype

torch.int64

In [118]:
# Reshape and View
my_torch2 = my_torch.reshape(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [119]:
# Reshape if we don't know the umber of items uing -1
my_torch2 = my_torch.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [120]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [122]:
# With reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [124]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [125]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [126]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [128]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [129]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [130]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## **Deep Learning with PyTorch 4**

**TENSOR MATH OPERATIONS**

In [131]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [132]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [133]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [134]:
# Add Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [135]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [136]:
# Substraction Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [137]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [138]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [139]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [140]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [141]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [142]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [143]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [144]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [145]:
tensor_a

tensor([1, 2, 3, 4])

In [146]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])